//
//  ClassTemplate.swift
//  ChickGen
//
//  Created by Christoph Pageler on 19.05.17.
//
//

import Foundation

class ClassTemplate {
    
    static func getTemplate() -> String {
        let template: String = """
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  {{ fileName }}
//  {{ projectName }}
//
//  Created by {{ author }} on {{ date }}
//
//

{% for import in imports %}
import {{ import }}{% endfor %}

{{class.accessControl}} class {{ class.name }} {
{% for attr in class.attributes %}
    {{attr.accessControl}} {{ attr.ref }} {{ attr.name }}: {{ attr.type }} {{ attr.defaultValue }}{{ attr.formattedDynamicAttribute }}{% endfor %}
{% for func in class.functions %}
    {{func.accessControl}}{{func.func}}{{ func.name }}({{ func.formattedParameters }}){{ func.formattedThrows }}{{ func.formattedReturn }} {
{% for bodyLine in func.bodyLines %}
        {{ bodyLine }}{% endfor %}

    }
{% endfor %}
}
"""
        return template
    }
    
}
