//
//  ClassTemplate.swift
//  ChickGen
//
//  Created by Christoph Pageler on 19.05.17.
//
//

import Foundation

class ClassTemplate {
    
    static func getTemplate() -> String {
        let template: String = "//\n" +
"// WARNING: THIS FILE IS AUTOGENERATED                 \n" +
"//          BY ChickGen 🐥                             \n" +
"// MORE INFO: github: cpageler93/ChickGen              \n" +            
"//                                                     \n" +
"//                                                     \n" +
"//  {{ fileName }}                                     \n" +
"//  {{ projectName }}                                  \n" +
"//                                                     \n" +
"//  Created by {{ author }} on {{ date }}              \n" +
"//                                                     \n" +
"//                                                     \n" +
"                                                       " +
"{% for import in imports %}                            \n" +
"import {{ import }}                                    " +
"{% endfor %}                                           \n" +
"                                                       \n" +
"public class {{ class.name }} {                        \n" +
"{% for attr in class.attributes %}                     \n" +
"   {{ attr.ref }} {{ attr.name }}: {{ attr.type }}       " +
"{% endfor %}                                           \n" +
"{% for func in class.functions %}                      \n" +
"   public func {{ func.name }}({{ func.formattedParameters }}) {{ func.formattedReturn }} { \n" +
"{% for bodyLine in func.bodyLines %}                   \n" +
"       {{ bodyLine }}                                  " +
"{% endfor %}                                           \n" +
"   }                                                   \n" +
"{% endfor %}                                           \n" +
"                                                       \n" +
"}                                                      \n"
        return template
    }
    
}
