//
//  EnumTemplate.swift
//  ChickGen
//
//  Created by Christoph Pageler on 25.07.17.
//

import Foundation

class EnumTemplate {
    
    static func getTemplate() -> String {
        let template: String = """
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  {{ fileName }}
//  {{ projectName }}
//
//  Created by {{ author }} on {{ date }}
//
//

public enum {{ enum.name }}: String {
{% for case in enum.cases %}
    case {{ case }}{% endfor %}

}

"""
        return template
    }
    
}

