//
//  ExtensionTemplate.swift
//  ChickGen
//
//  Created by Christoph Pageler on 30.07.17.
//

import Foundation

class ExtensionTemplate {
    
    static func getTemplate() -> String {
        let template: String = """
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  {{ fileName }}
//  {{ projectName }}
//
//  Created by {{ author }} on {{ date }}
//
//

{% for import in imports %}
import {{ import }}{% endfor %}

{{ext.accessControl}} extension {{ ext.name }}{{ ext.inheritance }} {
{% for attr in ext.attributes %}
    {{attr.accessControl}} {{ attr.ref }} {{ attr.name }}: {{ attr.type }} {{ attr.defaultValue }}{{ attr.formattedDynamicAttribute }}{% endfor %}
{% for func in ext.functions %}
    {{func.accessControl}}{{func.func}}{{ func.name }}({{ func.formattedParameters }}){{ func.formattedThrows }}{{ func.formattedReturn }} {
{% for bodyLine in func.bodyLines %}
        {{ bodyLine }}{% endfor %}

    }
{% endfor %}
}
"""
        return template
    }
    
}

