//
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  MasterClass.swift
//  Hello this is Test
//
//  Created by Author Name on 19. May 2017, 21:37:26
//
//

import Foundation

public class MasterClass {


}
