//
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  TestClass.swift
//  Project Name
//
//  Created by Author Name on 19. May 2017, 21:42:37
//
//

import Foundation

public class TestClass: MasterClass {

    foo: String?
    bar: String

}
