//
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  TodoItem.swift
//  Todo List
//
//  Created by Christoph Pageler on 19. May 2017, 21:46:00
//
//

import Foundation

public class TodoItem {

   let id: Int
   let title: String

}
