//
// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  GithubRepository.swift
//  Github Client
//
//  Created by Christoph Pageler on 19. May 2017, 23:09:12
//
//

import Foundation
import Quack

public class GithubRepository: QuackModel {

   var name: String?
   var fullName: String?
   var owner: String?


}
